#cloud-config
users:
  - name: obrienk
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNr8VXsiCWGs4rCD54kf1fP2CuIMEEFeJnZvnMp4BK1 karlobrien@github

package_update: true

packages:
  - git
  - curl
  - zsh

write_files:
  - path: /home/obrienk/.config/chezmoi/chezmoi.toml
    owner: obrienk:obrienk
    permissions: '0644'
    content: |
      [data]
        name = "Karl O Brien"
        email = "karlobrien@gmail.com"

runcmd:
  - usermod -s /usr/bin/zsh obrienk
  - curl -fsLS https://chezmoi.io/get | sh -s -- -b /usr/local/bin
  - sudo -u obrienk /usr/local/bin/chezmoi init --apply github.com/karlobrien/dotfiles
